clear all;
clc;
N=7;
M=7;
cont=0;
Nodos(1:N,1:M)=0;
Longest_Path=0;
filewrite=fopen('Caminos_Grid7x7_SP.txt','w');
for x_1=1:1:N;
    for y_1=1:1:M;
        cont=cont+1;
        Nodos(x_1,y_1)=cont;
    end;
end;
for x_1=1:1:N;
    for y_1=1:1:M;
        for x_2=1:1:N;
            for y_2=1:1:M;
                if x_1~=x_2 || y_1~=y_2;
                    n=x_2-x_1;
                    m=y_2-y_1;
                    Longest_Path=max(Longest_Path,abs(n)+abs(m));
                    D=0.*(1:(abs(n)+abs(m)));
                    if abs(n)>0;
                        D(1:abs(n))=1;
                    end;
                    P=uniqueperms(D);
                    N_path=length(P(:,1));
                    for i=1:1:N_path;
                        for j=1:1:(abs(n)+abs(m));
                            if j==1;
                                z_1=x_1;
                                z_2=y_1;
                                fprintf(filewrite,'%d',Nodos(z_1,z_2));
                            end;
                            if P(i,j)==1;
                                z_1=z_1+sign(n);
                                fprintf(filewrite,' %d',Nodos(z_1,z_2));
                            else
                                z_2=z_2+sign(m);
                                fprintf(filewrite,' %d',Nodos(z_1,z_2));
                            end;
                            if j==abs(n)+abs(m);
                                fprintf(filewrite,'\n');
                            end;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;